apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wger-app-secret
  namespace: wger
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: wger-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: wger-postgres-secrets
        property: wger-db-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Fail
    - secretKey: password
      remoteRef:
        key: wger-postgres-secrets
        property: wger-db-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Fail
