apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pool1-sabnzbd-appdata
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-pool1-sabnzbd-appdata
    volumeAttributes:
      server: 10.10.1.46
      share: /pool-1 # Mounting the root of pool-1
  mountOptions:
    - nfsvers=4.1
    - tcp
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-appdata
  namespace: sabnzbd
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" 
  volumeName: pv-pool1-sabnzbd-appdata
  resources:
    requests:
      storage: 1Ti