apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-app-secret
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: gitea-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-secrets
        property: authentik-db-username
    - secretKey: password
      remoteRef:
        key: postgres-secrets
        property: authentik-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3-credentials
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: cnpg-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "k8s operators b2 bacukp credentials"
        property: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "k8s operators b2 bacukp credentials"
        property: password
