apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-daily-backup
  namespace: authentik
spec:
  # Sec Min Hour Day Month DayOfWeek
  schedule: "0 0 2,14 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-db
  immediate: true
