apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-daily-backup
  namespace: authentik
spec:
  schedule: "5 2 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-db
  immediate: true
