extends: default

rules:
  line-length: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  truthy: disable
  document-start: disable  # for handling k8s manifests with multiple '---'
