apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: adguard
  namespace: traefik
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - "adguard.mcmn.me"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: adguard-external
          port: 3000
          weight: 1
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: rube.homelab.local  # defined on Unifi router
  ports:
    - port: 3000
      targetPort: 3000
      name: http
