apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-10"
resources:
- ns.yaml
- clusterrole-full-rbac.yaml
- clusterrolebinding-full-rbac.yaml
        # Enable job cleanup and set retention policies
          # Configure job TTL and cleanup
helmCharts:
- includeCRDs: true
  name: cloudnative-pg
  namespace: cloudnative-pg
  releaseName: cloudnative-pg-operator
  repo: https://cloudnative-pg.github.io/charts
  valuesInline:
    config:
      data:
        ENABLE_AZURE_PVC_UPDATES: "false"
        FAILED_JOB_TTL_SECONDS_AFTER_FINISHED: "7200"
        INHERITED_ANNOTATIONS: argocd.argoproj.io/sync-wave
        INHERITED_LABELS: app.kubernetes.io/managed-by
        JOB_TTL_SECONDS_AFTER_FINISHED: "3600"
  version: 0.28.3
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: cloudnative-pg
