apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-proxmox
helmCharts:
- includeCRDs: true
  name: proxmox-csi-plugin
  namespace: csi-proxmox
  releaseName: csi-proxmox
  repo: oci://ghcr.io/sergelogvinov/charts
  valuesFile: values.yaml
  version: 0.5.7
resources:
- ns.yaml
- external-secret.yaml
