apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki-stack
resources:
- ns.yaml
- loki-http-route.yaml
- external-secret.yaml
helmCharts:
- includeCRDs: true
  name: loki
  namespace: loki-stack
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  valuesFile: values.yaml
  version: 7.0.0
