apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki
  namespace: loki-stack
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - loki.mcmn.me
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: loki-gateway
          port: 80
          weight: 1