apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-app-secret
  namespace: sparky-fitness
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: sparky-app-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: sparkyfitness-postgres-secrets
        property: sparky-db-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Fail
    - secretKey: password
      remoteRef:
        key: sparkyfitness-postgres-secrets
        property: sparky-db-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Fail
