apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: sparky-daily-backup
  namespace: sparky-fitness
spec:
  # Sec Min Hour Day Month DayOfWeek
  schedule: "0 0 2,14 * * *"
  backupOwnerReference: self
  cluster:
    name: sparkyfitness-db
  immediate: true
