apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wger-django-secret
  namespace: wger
  labels:
    app.kubernetes.io/name: wger-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: wger-django-secret
    creationPolicy: Owner
  data:
    - secretKey: secret-key
      remoteRef:
        key: "WGER Configuration"
        property: secret-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wger-jwt-secret
  namespace: wger
  labels:
    app.kubernetes.io/name: wger-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: wger-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: signing-key
      remoteRef:
        key: "WGER Configuration"
        property: signing-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wger-mail-secret
  namespace: wger
  labels:
    app.kubernetes.io/name: wger-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: wger-mail-secret
    creationPolicy: Owner
  data:
    - secretKey: mail-password
      remoteRef:
        key: "Mailgun WGER"
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
