apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-root-password
  namespace: doplarr
  labels:
    app.kubernetes.io/name: doplarr-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: doplarr-discord-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: doplarr-discord-token
        property: token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: overseerr-api-token
  namespace: doplarr
  labels:
    app.kubernetes.io/name: doplarr-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: overseerr-api-token
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: overseerr-api-token
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: id
      remoteRef:
        key: overseerr-api-token
        property: id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
