apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: tunnel-credentials
    creationPolicy: Owner # Add this line
  dataFrom:
    - extract:
        key: cloudflared-labber-tunnel-credentials
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
