apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

resources:
- httproute.yaml
- external-secret.yaml

helmCharts:
- includeCRDs: true
  name: authentik
  namespace: authentik
  releaseName: authentik
  repo: https://charts.goauthentik.io/
  valuesFile: values.yaml
  version: 2026.5.2
