global:
  revisionHistoryLimit: 3
authentik:
  secret_key: ""
  existingSecret:
    secretName: "authentik-configuration-secrets"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: false

  postgresql:
    password: ""
  envValueFrom:
  AUTHENTIK_POSTGRESQL__USER:
    secretKeyRef:
      name: authentik-app-secret
      key: username
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: authentik-app-secret
      key: password
  AUTHENTIK_EMAIL__HOST:
    secretKeyRef:
      name: authentik-configuration-secrets
      key: smtp-server
  AUTHENTIK_EMAIL__FROM:
    secretKeyRef:
      name: authentik-configuration-secrets
      key: smtp-username
  AUTHENTIK_EMAIL__USERNAME:
    secretKeyRef:
      name: authentik-configuration-secrets
      key: smtp-username
  AUTHENTIK_EMAIL__PASSWORD:
    secretKeyRef:
      name: authentik-configuration-secrets
      key: smtp-password

  env:
    AUTHENTIK_POSTGRESQL__HOST: "authentik-db-rw.authentik.svc.cluster.local"
    AUTHENTIK_POSTGRESQL__PORT: "5432"
    AUTHENTIK_POSTGRESQL__NAME: "authentik"
    AUTHENTIK_EMAIL__PORT: "587"
    AUTHENTIK_EMAIL__USE_TLS: "true"
    AUTHENTIK_EMAIL__USE_SSL: "false"

# using traefik with External-DNS, this does not need to be managed via the helm chart
server:
  ingress:
    enabled: false

# using CNPG operator, no need for Bitnami chart
postgresql:
  enabled: false
