global:
  revisionHistoryLimit: 3

  env:
    # SERVER
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-configuration-secrets
          key: secret_key
    # DB
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-app-secret
          key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-app-secret
          key: password
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: "authentik-db-rw.authentik.svc.cluster.local"
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: "authentik"
    # EMAIL
    - name: AUTHENTIK_EMAIL__HOST
      valueFrom:
        secretKeyRef:
          name: authentik-configuration-secrets
          key: smtp-server
    - name: AUTHENTIK_EMAIL__FROM
      valueFrom:
        secretKeyRef:
          name: authentik-configuration-secrets
          key: smtp-username
    - name: AUTHENTIK_EMAIL__USERNAME
      valueFrom:
        secretKeyRef:
          name: authentik-configuration-secrets
          key: smtp-username
    - name: AUTHENTIK_EMAIL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-configuration-secrets
          key: smtp-password
    - name: AUTHENTIK_EMAIL__PORT
      value: "587"
    - name: AUTHENTIK_EMAIL__USE_TLS
      value: "true"
    - name: AUTHENTIK_EMAIL__USE_SSL
      value: "false"
authentik:
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: false

# using traefik with External-DNS, this does not need to be managed via the helm chart
server:
  ingress:
    enabled: false

# using CNPG operator, no need for Bitnami chart
postgresql:
  enabled: false
