apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: snapshot-controller

resources:
- ns.yaml

helmCharts:
- includeCRDs: true
  name: snapshot-controller
  namespace: snapshot-controller
  releaseName: snapshot-controller
  repo: https://piraeus.io/helm-charts/
  valuesFile: values.yaml
  version: 5.0.4
