apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- ns.yaml
- cloudflare-external-secret.yaml
- mcmn-me-cloudflare-cluster-issuer.yaml
- internal-selfsigned-cluster-issuer.yaml
helmCharts:
- includeCRDs: true
  name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
  version: v1.20.2
