apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-external
  namespace: gateway
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
spec:
  addresses:
  - type: IPAddress
    value: 172.16.18.30
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.labber.mcmn.io"
      allowedRoutes:
        namespaces:
          from: All