apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - appdata-pvc.yaml
  - shared-media-pvc.yaml
  - http-route.yaml
  - external-secret.yaml
helmCharts:
  - name: plex-media-server
    namespace: plex
    repo: https://plexinc.github.io/pms-docker
    version: 0.2.1
    releaseName: plex
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - target:
      kind: StatefulSet
      name: plex-plex-media-server
      namespace: plex
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: plex-plex-media-server
      spec:
        template:
          spec:
            containers:
              - name: plex-plex-media-server-pms
                volumeMounts:
                  - name: pms-config
                    mountPath: /config
                    subPath: appdata/linuxserver-plex/config
