apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pool0-media-plex
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: pv-pool0-media-plex
    volumeAttributes:
      server: 10.10.1.46
      share: /pool-0/media
  mountOptions:
    - nfsvers=4.1
    - tcp
    - noatime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-library-plex
  namespace: plex
  labels:
    velero.io/exclude-from-backup: "true" # Don't let Velero backup 10TB of movies!
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-pool0-media-plex
  resources:
    requests:
      storage: 1Ti
