image:
  repository: linuxserver/plex
  tag: 1.43.1
  pullPolicy: IfNotPresent

hostNetwork: false

# ---------------------------------------------------------
# The 'pms' block: Where this specific chart expects app logic
# ---------------------------------------------------------
pms:
  claimSecret:
    name: "plex-configuration-secrets"
    key: "claim-code"

  configExistingClaim: pvc-plex-appdata

  resources:
    limits:
      gpu.intel.com/xe: 1
    requests:
      cpu: 100m
      memory: 500Mi

  securityContext:
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 44  # 'video'
      - 107 # 'render'

  livenessProbe:
    httpGet:
      path: /identity
      port: 32400
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 1
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /identity
      port: 32400
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 1
    failureThreshold: 3

extraVolumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-media-library-plex

extraVolumeMounts:
  - name: data
    mountPath: /data

extraEnv:
  TZ: America/Toronto
  PUID: "1000"
  PGID: "1000"
