apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1passwordconnect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/macmandr197/k8s-homelab.git
    targetRevision: main
    path: infra/controllers/1passwordconnect
  destination:
    server: https://kubernetes.default.svc
    namespace: 1passwordconnect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
  