# Critical: CSI-Proxmox must be deployed after Cilium (wave 1)
# Storage layer depends on networking being fully operational
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-proxmox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/macmandr197/k8s-homelab.git
    targetRevision: main
    path: infra/storage/csi-driver-proxmox
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-proxmox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    jsonPointers:
    - /data
  - group: ""
    kind: Secret
    jsonPointers:
    - /data