apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - git:
      repoURL: https://github.com/macmandr197/k8s-homelab.git
      revision: main
      directories:
      - path: infra/controllers/*
      - path: infra/networking/*
      - path: infra/storage/*
      - path: infra/database/*/*
      - path: infra/crds

      # EXCLUDES: These are managed by standalone Apps for Sync Wave control (Wave 0/1)
      # or are the ArgoCD controller itself.
      - path: infra/controllers/1passwordconnect
        exclude: true
      - path: infra/controllers/external-secrets
        exclude: true
      - path: infra/networking/cilium
        exclude: true
      - path: infra/storage/csi-driver-proxmox
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      revisionHistoryLimit: 3
      source:
        repoURL: https://github.com/macmandr197/k8s-homelab.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - Replace=false
        - IgnoreMissingTemplate=true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 5
      ignoreDifferences:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
      - group: gateway.networking.k8s.io
        kind: Gateway
        jsonPointers:
        - /status
      