apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ignoreApplicationDifferences:  # to allow sub-apps to have their sync policy manually disabled, temporarily
  - jsonPointers:
    - /spec/syncPolicy
  generators:
  - git:
      repoURL: https://github.com/macmandr197/k8s-homelab.git
      revision: main
      directories:
      - path: my-apps/*/*
  template:
    metadata:
      name: 'my-apps-{{path.basename}}'
    spec:
      project: my-apps
      revisionHistoryLimit: 3
      source:
        repoURL: https://github.com/macmandr197/k8s-homelab.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - Replace=false
        - IgnoreMissingTemplate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
        - /status
      - group: external-secrets.io
        kind: ExternalSecret
        jsonPointers:
        - /status
        - /metadata/generation

      info:
      - name: 'Description'
        value: 'Application: {{path.basename}}'
