apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  # Add a finalizer to ensure that the project is deleted from ArgoCD if this file is ever removed.
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: "Infrastructure components like controllers, networking, and storage."
  sourceRepos:
  - https://github.com/macmandr197/k8s-homelab.git
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'