# Snapshot Controller
# Storage layer component - manages VolumeSnapshot CRDs and lifecycle
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/macmandr197/k8s-homelab.git
    targetRevision: main
    path: infra/storage/snapshot-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: snapshot-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
