apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-driver-nfs
helmCharts:
- includeCRDs: true
  name: csi-driver-nfs
  namespace: csi-driver-nfs
  releaseName: csi-driver-nfs
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  valuesFile: values.yaml
  version: 4.13.2
resources:
- ns.yaml
