apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml
- external-secret.yaml
- gateway-external.yaml
- external-services/adguard-http-route.yaml
- external-services/haas-http-route.yaml
- external-services/portainer-http-route.yaml
- external-services/stirling-http-route.yaml


helmCharts:
- includeCRDs: true
  name: traefik
  namespace: traefik
  releaseName: traefik
  repo: https://traefik.github.io/charts
  valuesFile: values.yaml
  version: 39.0.0

generatorOptions:
  disableNameSuffixHash: true
